# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "753172984754-terragrunt-tfstate-dev"
    encrypt = true
    key     = "./terraform.tfstate"
    region  = "ap-northeast-1"
  }
}
