name: test terragurnt action

on: workflow_dispatch
  #  pull_request:
  #    branches:
  #      - main
  #    types:
  #      - open

defaults:
  run:
    shell: bash -euo pipefail {0}

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: echo GITHUB_WORKSPACE
        run: |
          echo "${{ github.workspace }}"
      - name: echo rootdir files
        run: |
          ls -la "${{ github.workspace }}"
        working-directory: "./env/dev"
