name: test terragurnt action

on: workflow_dispatch
  #  pull_request:
  #    branches:
  #      - main
  #    types:
  #      - open

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: echo GITHUB_WORKSPACE
        run: |
          echo "${{ github.workspace }}"
